//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOutBusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class workoutactive
    {
        public int id { get; set; }
        public Nullable<int> workoutid { get; set; }
        public Nullable<System.TimeSpan> starttime { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<System.TimeSpan> endtime { get; set; }
        public string comment { get; set; }
        public Nullable<bool> currentstatus { get; set; }
    
        public virtual workoutcollection workoutcollection { get; set; }
    }
}
