//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOutBusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class workoutcollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workoutcollection()
        {
            this.workoutactives = new HashSet<workoutactive>();
        }
    
        public string workouttitle { get; set; }
        public string workoutnote { get; set; }
        public Nullable<double> caloriesburnpermin { get; set; }
        public Nullable<int> categoryid { get; set; }
        public int workoutid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workoutactive> workoutactives { get; set; }
        public virtual workoutcategory workoutcategory { get; set; }
    }
}
